### ISSUE TITLE
Mark Scheme checklist

### ISSUE THREAD

**Issue by samjesus8** [samjesus8/CCCU_AdvancedOperatingSystems_Assignment1#1]
# Assignment Checklist

- [x] Display Menu using entire screen
- [x] Select correctly & launch on a clean screen
- [x] Launch separate menu (place holder) files
- [x] Ability to exit at any prompt via the “Bye” command (case insensitive)
- [x] Prompt users if they really want to exit via a Y/n option (case insensitive) & repeat question until a valid choice is made
- [x] After completion of a selected simulator user returns back to menu
- [x] Suitable comments in code (comments must not exceed code)
- [x] Usage of colour in the menu system
- [x] Validate user correctly on entry (login correctly)
- [x] Validate user password on entry (login correctly)
- [x] Usage of appropriate functions (implemented)
- [x] Correct usage of Global/Local variables
- [x] Simple animation/ loading bar when menu start/exits & selection of simulator
- [x] Create separate admin script to add/ modify users to a database file
- [x] Usernames and passwords are case insensitive & validated
- [x] On user creation request password/pin twice & check if both entries are the same
- [x] Ability to delete user given correct PIN
- [ ] Ability to rest user password given correct PIN
- [x] PIN validation on creation
- [x] Accurate log recorded for user usage
- [x] Complete implementation of admin script for usage analysis as outlined
- [x] Correct implementation of sim data configuration & usage
- [x] Correct implementation of LIFO & FIFO scripts
- [x] Correct and complete implementation (as outlined above)
- [x] 800 words write up
